/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myparty;

/**
 *
 * @author silentwraith
 */
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.*;
public class loginn extends javax.swing.JFrame {

    public JFrame frame;
    Connection connection = null;
    static int f=0;
    int co=0;
    /**
     * Creates new form loginn
     */
    public loginn() {
        initComponents();
      //  this.setUndecorated(true);
       // this.setAlwaysOnTop(true);
    //    this.setResizable(false);
        //this.setVisible(true);
        connection = connectt.dbConnector();
        Toolkit tk = Toolkit.getDefaultToolkit();
       // int xsize = (int) tk.getScreenSize().getWidth();
        //int ysize = (int) tk.getScreenSize().getWidth();
        //this.setSize(xsize,ysize);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldUN = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        regist = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(254, 254, 254));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(253, 128, 128));
        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 250, 250));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 20));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 250, 250));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, 30));

        textFieldUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUNActionPerformed(evt);
            }
        });
        getContentPane().add(textFieldUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 180, 30));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, 30));

        btnLogin.setBackground(new java.awt.Color(30, 144, 255));
        btnLogin.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(212, 212, 212));
        btnLogin.setText("LogIn");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 150, 40));

        regist.setBackground(new java.awt.Color(139, 0, 0));
        regist.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        regist.setForeground(new java.awt.Color(212, 212, 212));
        regist.setText("Register");
        regist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registActionPerformed(evt);
            }
        });
        getContentPane().add(regist, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 160, 40));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(212, 212, 212));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myparty/abc.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 500));

        jLabel4.setBackground(new java.awt.Color(44, 44, 44));
        jLabel4.setFont(new java.awt.Font("Te X Gyre Heros Condensed", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(212, 212, 212));
        jLabel4.setText("   PartySeeker");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 200, 50));

        jButton1.setBackground(new java.awt.Color(0, 100, 0));
        jButton1.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(212, 212, 212));
        jButton1.setText("Guest Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 320, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try{
            String query="select * from employeedata where username=? and password=?";
            PreparedStatement pst=connection.prepareStatement(query);
            pst.setString(1, textFieldUN.getText());
            pst.setString(2, passwordField.getText());
          
            ResultSet rs = pst.executeQuery();
            
            
            int count=0;
            while(rs.next()){
                count=count+1;
            }
            
            if(count==1)
            {
                JOptionPane.showMessageDialog(null, "Username and password is correct");
                //frame.dispose();
                new Party(f).setVisible(true);
            }
            else if(count>1)
            {
                JOptionPane.showMessageDialog(null, "Duplicate Username and password");
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Username and password is incorrect");
            }
            
            rs.close();
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void textFieldUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUNActionPerformed

    private void registActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registActionPerformed
        try{
            String queryy="select * from employeedata";
            PreparedStatement pstt=connection.prepareStatement(queryy);
            ResultSet rss = pstt.executeQuery();
            while(rss.next()){
                co=co+1;
            }
            System.out.println(co);
            String query="insert into employeedata(username,password,userid) values('"+textFieldUN.getText()+"','"+passwordField.getText()+"',"+co+1+")";
        Statement st= connection.createStatement();
        st.executeUpdate(query);
        textFieldUN.setText(null);
        passwordField.setText(null);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_registActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        f=1;
        new Party(f).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton regist;
    private javax.swing.JTextField textFieldUN;
    // End of variables declaration//GEN-END:variables
}
