/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myparty;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author silentwraith
 */
public class Party extends javax.swing.JFrame {
    static String cityy;
    static String sortbyy;
    static String occasionn;
    static int ff;
    /**
     * Creates new form Party
     */
    public Party(int f) {
        initComponents();
        ff=f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        sortCB = new javax.swing.JComboBox<>();
        occassionCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(30, 144, 255));
        jButton1.setFont(new java.awt.Font("Bitstream Charter", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(212, 212, 212));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 330, 50));

        sortCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "rating", "real_distance", "cost" }));
        sortCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortCBActionPerformed(evt);
            }
        });
        getContentPane().add(sortCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 310, 40));

        occassionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Birthdays", "Anniversaries", "Weddings", "Graduations", "Holidays", "Festivities", "Just Becoz", "Quick bites" }));
        occassionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occassionCBActionPerformed(evt);
            }
        });
        getContentPane().add(occassionCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 310, 40));

        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(212, 212, 212));
        jLabel1.setText("          PartySeeker");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 400, 60));

        cityTF.setText("Enter Your City");
        getContentPane().add(cityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 310, 42));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myparty/abcd.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        cityy = cityTF.getText();
        sortbyy = (String) sortCB.getSelectedItem();
        occasionn = (String) occassionCB.getSelectedItem();

        try {
            
            new joke(cityy, sortbyy,occasionn,ff).setVisible(true);
            
        } catch (Exception ex) {
            Logger.getLogger(Party.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void occassionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occassionCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_occassionCBActionPerformed

    private void sortCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortCBActionPerformed

    
        /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Party.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Party(ff).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cityTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> occassionCB;
    private javax.swing.JComboBox<String> sortCB;
    // End of variables declaration//GEN-END:variables
}
